<?php
require_once __DIR__ . '/lib/site.php';
page_header('Finanse w Polsce', 'Przewodniki, źródła i kalkulatory dla osób prywatnych oraz profesjonalistów na polskim rynku finansowym.', '/', 'start');
$all = articles();
?>
<section class="hero"><div class="container hero-grid">
  <div><span class="eyebrow"><span class="pulse"></span> Wiedza, która pomaga decydować</span><h1>Finanse w Polsce.<br><em>Zrozum zanim zdecydujesz.</em></h1><p class="hero-lead">Kredyty, oszczędności, inwestycje i finanse firmy — w jednym miejscu, prostym językiem, z odnośnikami do oficjalnych źródeł.</p><div class="hero-actions"><a class="button button-primary" href="/tematy.php">Przeglądaj tematy <span aria-hidden="true">↗</span></a><a class="button button-light" href="/narzedzia.php">Otwórz narzędzia <span aria-hidden="true">→</span></a></div><div class="hero-proof"><span>15 praktycznych przewodników</span><span>6 obszarów finansów</span><span>4 kalkulatory</span></div></div>
  <div class="hero-panel" aria-label="Ścieżki tematyczne"><div class="panel-head"><span>OD CZEGO ZACZĄĆ</span><span class="panel-symbol">↗</span></div><a href="/artykul.php?slug=rrso-i-koszt-kredytu"><span class="panel-icon">01</span><span><strong>Porównuję kredyt</strong><small>RRSO, koszty i warunki</small></span><span>→</span></a><a href="/artykul.php?slug=poduszka-finansowa"><span class="panel-icon">02</span><span><strong>Buduję oszczędności</strong><small>Rezerwa i bezpieczeństwo</small></span><span>→</span></a><a href="/artykul.php?slug=plynnosc-firmy"><span class="panel-icon">03</span><span><strong>Zarządzam firmą</strong><small>Płynność i finansowanie</small></span><span>→</span></a><div class="panel-foot">Wybierz problem, który chcesz rozwiązać dziś.</div></div>
</div></section>
<section class="section container"><div class="section-heading"><div><span class="section-kicker">MAPA TEMATÓW</span><h2>Wybierz obszar finansów</h2><p>Od codziennych decyzji po analizę kapitału w firmie.</p></div><a class="text-link" href="/tematy.php">Wszystkie przewodniki →</a></div><div class="topic-grid">
<?php foreach (topics() as $slug => [$name, $description, $icon]): ?><a class="topic-card" href="/tematy.php?topic=<?= e($slug) ?>"><span class="topic-icon" aria-hidden="true"><?= e($icon) ?></span><span><strong><?= e($name) ?></strong><small><?= e($description) ?></small></span><span class="topic-arrow" aria-hidden="true">↗</span></a><?php endforeach; ?>
</div></section>
<section class="section section-soft"><div class="container"><div class="section-heading"><div><span class="section-kicker">NAJWAŻNIEJSZE PRZEWODNIKI</span><h2>Dobre decyzje zaczynają się od pytań</h2><p>Krótkie wyjaśnienia, lista rzeczy do sprawdzenia i źródła na końcu każdego tekstu.</p></div></div><div class="article-grid"><?php foreach (['rrso-i-koszt-kredytu','lokaty-i-bfg','obligacje-skarbowe','kredyt-hipoteczny','podatek-od-inwestycji','plynnosc-firmy'] as $slug) article_card($slug, $all[$slug]); ?></div></div></section>
<section class="section container"><div class="split-promo"><div><span class="section-kicker">NARZĘDZIA</span><h2>Sprawdź liczby na własnym przykładzie.</h2><p>Oblicz orientacyjną ratę, cel poduszki finansowej, przyszłą wartość oszczędności lub RRSO harmonogramu.</p><a class="button button-primary" href="/narzedzia.php">Przejdź do kalkulatorów ↗</a></div><div class="promo-figure"><span>100 000 zł</span><small>Przykładowa kwota kredytu</small><div class="promo-rule"></div><strong>Twoje założenia. Twój wynik.</strong><p>Bez konta i bez wysyłania danych na zewnętrzny serwer.</p></div></div></section>
<section class="section section-soft"><div class="container source-band"><div><span class="section-kicker">WIARYGODNOŚĆ</span><h2>Źródło jest częścią odpowiedzi.</h2><p>Materiały bazują na informacjach NBP, KNF, UOKiK, BFG, GUS, Ministerstwa Finansów i oficjalnego portalu PPK. Ostatni przegląd: <?= e(REVIEW_DATE) ?>.</p></div><a class="button button-outline" href="/zrodla.php">Zobacz źródła →</a></div></section>
<?php page_footer(); ?>
